### PR TITLE
Chain together path and time parameterization

### PR DESCRIPTION
**Pull request by jonbinney**
This PR adds a function, `trajectory_for_path()`, which takes a path as a sequence of points in joint space (representing a piecewise linear path in joint space) and returns continuous piecewise polynomial functions for joint positions, velocities, acclerations and jerks w.r.t. time that respect the provided velocity/acceleration/jerk limits while following the path in the minimum time.

Caveat: the trajectory has zero velocity and acceleration at each waypoint, and is only "optimal" within that constraint.

Here is the output of the example script called `demo` which finds a time parametrization for a 2-joint case with 4 waypoints. (waypoints in blue) and evenly spaced points in the time parametrization chosen (in red):

path

Here are the joint positions, velocities, accelerations, and jerks vs. time. Joint 1 is in red and joint 2 is in blue.

trajectory

Next steps:
- harden this code. It needs more unit tests to make sure there aren't any major corner cases.
- add a simple ROS node that sends some time-optimal trajectories to our fanuc arm using the driver's FollowJointTrajectory action
- geometrically smooth the interface between path segments using pilz's polynomial blending approach
- allow non zero velocities at waypoints in the paths (@mahmoud-a-ali I could use your help with this part)
- put everything together

@bhomberg @gavanderhoorn  @mahmoud-a-ali @wongkaiweng @sosentos

### CODE REVIEW

**Comment by mahmoud-a-ali** [comment]
Great work!
I was modifying the non-zero velocities 7-segments before Christmas leave. I will resume and commit it asap

**Comment by jonbinney** [comment]
I've updated this branch with a couple improvements:
- a demo trajectory using industrial_robot_simulator, using a simulated fanuc m20ib
- a simple but non-optimal solver for 7 segment trajectories for non-zero starting and end velocities (I missed https://github.com/iron-ox/trajectory_smoothing/pull/8 - it will supersede what i've done)
- some improvements to plotting

I did try this on our arm, but had some issues. Even though the trajectory has valid values for position, velocity, acceleration, and jerk, the robot faults (complains about jerk or acceleration that is too high). I'm not yet sure whether this is caused by the quintic spline interpolation in joint_trajectory_controller, or if it is a result of the discrete way that the fanuc controller estimates jerk. I've collected a bagfile with both the goal trajectory and the commands the driver sends to the robot controller, but I still need to analyze it.

/cc @mahmoud-a-ali  @gavanderhoorn @bhomberg

**Comment by jonbinney** [comment]
I'm going to go ahead and merge this since https://github.com/iron-ox/trajectory_smoothing/pull/8/files will depend on it.

**Comment by gavanderhoorn** [comment]
> I've collected a bagfile with both the goal trajectory and the commands the driver sends to the robot controller, but I still need to analyze it.

If you could make that available to me as well, I'd be interested.

Please also make a backup of your controller after such tests, as there are files on the controller which could tell us more about what it's complaining about exactly.

**Pull request merged**
