### PR TITLE
[WIP] Discrete time parameterization algorithm

### PR DESCRIPTION
**Pull request by jonbinney**
I think that we can solve the "time parameterization for a given geometric path" problem with a discrete algorithm with the following properties:
- very close to optimal for almost all cases
- reasonable result even for pathological cases
- polynomial time: n^3 in the number of points in the resulting trajectory

Even though we have to lose some precision by discretizing time, we must do this anyway before sending commands to the robot controller.

The overall process would be:
1. Plan a piecewise-linear geometric path in joint space using some motion planner (moveit/etc)
2. Apply geometric blending to the path to make it smooth (e.g. arc-based blending we have in this package)
3. Reformulate path as a function of a single variable, "s"
4. Run the discrete-time algorithm from this PR to come up with the trajectory.

Because we do the "s" parameterization before running this algorithm, we can assume a few things about the path:
- it only needs to operate on a 1d space ("s")
- the velocity (ds/dt) will always be positive
- the limits on jerk, velocity, and acceleration will vary depending on s, because of the shape of the original path

The varying limits is the trickiest part. So far I've implemented velocity limits that vary with s. Acceleration and jerk will be slightly trickier, but I think doable.

/cc @mahmoud-a-ali @gavanderhoorn @bhomberg

### CODE REVIEW

**Comment by jonbinney** [comment]
Here's how the algorithm works, roughly:
```
position =  p0
velocity = v0
acceleration = a0
while we haven't reached our goal:
   for each jerk in [j_max, 0.0, j_max]:
      - compute position, velocity and jerk at the next timestep assuming this jerk
      - if any of them are outside of our limits, don't use this jerk value
      - compute_fastest_possible_stop()
      - if we found some valid stopping trajectory starting at this point, we can use this jerk value
```
This is effectively a completely greedy algorithm - at each point in time we use the maximum jerk that doesn't put us into a state where we would be unable to bring the robot back to zero velocity without violating limits or overshooting the goal.

This works because going slower is always safer, and going faster is (almost) always more optimal, as long as we can stop. Here's an example trajectory. The dotted lines in the velocity plot are the velocity limits (they vary depending on the value of "s" - so they can depend on both the path geometry and the robot kinematics, as well as the current payload, or whatever we want!).

Figure_1

The cubic running time of the algorithm should be fine - it takes a few seconds in un-optimized python, but I think could be run in a tenth of a second or so in C++. Also, the algorithm can be run online, and the computation at each time step should (i think) take much less time than the ITP. So the algorithm would lookahead at each timestep  as the robot moves, and decide if it can speed up, or if it needs to slow down to avoid future problems.

Sorry if I'm not making much sense; I just got this working and wanted to send it out before I go to sleep.

**Comment by mahmoud-a-ali** [comment]
a promising approach especially it can handle the relationship between the variable jerk limits considering different velocity / payload. 

if I understand correctly this demo considers the s-domain trajectory as s changes bet. 0 to 30 and s_dot start and end with 0. I am wondering if you came up with a new way to project the joint limits into the s-domain for the arc-based blending segment as this was the main issue for the previous approach?

**Comment by jonbinney** [comment]
@mahmoud-a-ali one nice aspect of this algorithm doesn't require projecting the limits onto s. Instead, the algorithm chooses possible values for s, and then can ask a function "are these valid". Assume that the algorithm is considering values of s1, s2, s3, and s4 for timesteps 1 through 4. It can call a function `is_valid(s1, s2, s3, s4)`. `is_valid` can convert the s values to joint space values, and then compute the discrete velocity, acceleration, and jerk using the same method that the fanuc controller uses. Then it can check whether each joint is within limits.

**Comment by jonbinney** [comment]
Update: I'm still trying to find the best way of handling the end of the trajectory. It always gets close to zero velocity and zero acceleration, but hitting both at the exact same moment is the tricky bit. We need to hit a timestep where both velocity and accelration in the S domain are less than their per-timestep limits, so that we can then drop the arm to exactly zero velocity. Working on this today and tomorrow.

**Comment by gavanderhoorn** [comment]
What about something similar to the IPTP? So a two or multi-iteration approach? Do an initial run, see what the error is between `(0-vel, 0-acc, 0-jerk)` and the result, then distribute that error over "the rest" of the trajectory?

**Comment by jonbinney** [comment]
While working on an end to end demo, I've found a problem with the deceleration part of the algorithm. It makes an implicit assumption that the acceleration limit on `s` relative to time is constant. This is of course a bad assumption - the acceleration limit on `s` depends on what direction the geometric path is moving in joint space at that point. It might be ok though; we only have to assume constant max acceleration for the duration of the deceleration, not for the entire path.

I might switch the  deceleration part of the algorithm over to continuous space. The advantage is that it would be easier to handle the max acceleration (it would still have to be constant, but at least it would enforce that properly). The disadvantage is that their may be some funniness splicing together a discrete trajectory and a sampled continuous trajectory.

**Comment by gavanderhoorn** [comment]
@jonbinney: do you already have the demo available somewhere? Might be possible to point some additional "eyes" to it.

**Comment by jonbinney** [comment]
I'm going to go ahead and merge what I've got so far on the discrete approach (it doesn't work) and move on to trying other approaches. The discrete "demo" (just uses a hardcoded simple trajectory) is in scripts/discrete_demo. Here are the problems that I haven't found solutions to:
1. Discretization must be very fine grained or else there won't be any timestep that is close enough to the goal position, has zero velocity, and zero acceleration.
2. The algorithm works by moving the transition points between max jerk and min jerk sections around in a very controlled way, until the trajectory ends exactly at the end of the path. Unfortunately there are some conditional branches in the code (e.g. if jerk is too high here, do this other thing) that can cause the trajectory to suddenly jump past the end of the path. This is different from problem (1), which is just plain old discretization error.
3. During the deceleration section of the trajectory, there is no greedy way (that i can find) to both stop as quickly as possible and also avoid decelerating too quickly in the case that the acceleration limit is lower further along the path (for example if there is a tight turn up ahead on the path in joint space).

Problem (1) is really just a matter of increasing the resolution, although based on the running times I've seen, this might require using clever binary-search methods to speed things up. (2) might be solvable with enough engineering effort to deeply understand all the possible branches, and make sure they don't mess things up. Then again, maybe not. (3) is more of a fundamental algorithmic problem. We could work around it by trying a fixed set of possible max deceleration values, but this would increase the running time and also severely reduce the optimality of the solutions.

At this point I still feel about 50% confidence that there is some discrete algorithm of this basic form that would work quite well, but I also feel that there are a lot of difficult problems to solve before it could (maybe) be useful. I'm going to go back to using piecewise-polynomial functions, and try to find ways to remove some of the weaknesses of that approach. In particular, find a way to avoid stopping when moving between segments in a trajectory, and find a way to let the velocity/acceleration/jerk limits vary depending on kinematics, payload, etc.

**Comment by jonbinney** [comment]
Hmm... looks like I don't have write access to this repo anymore. I've merged this PR into the master branch in my own fork; I think I'll probably continue development there from now on: https://github.com/jonbinney/trajectory_smoothing

**Pull request closed without merging**
